- name: Install maven
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: installed
  loop: 
  - maven
  - mysql

- name: Install PyMySQL
  ansible.builtin.pip:
    name: "{{ item }}"
    executable: pip3.9
  loop:
  - PyMySQL
  - cryptography

- name: Install maven dependencies
  ansible.builtin.command: mvn clean package
  args:
    chdir: /app

- name: Move and rename jar file
  ansible.builtin.command: "mv /app/target/{{ component }}-1.0.jar /app/{{ component}}.jar"